theme: jekyll-theme-minimal
title: Pratheek B
description: PhD candidate at CSA, IISc.
contact: pratheekb@iisc.ac.in
show_downloads: false
is_user_page: false
logo: assets/751DA092-A1CE-4CCD-B36F-A824F2FE51A6_1_201_a.jpeg
